apiVersion: v1
kind: Config

clusters:
- name: minikube
  cluster:
    server: https://host.docker.internal:56078
    insecure-skip-tls-verify: true

contexts:
- name: jenkins-context
  context:
    cluster: minikube
    user: jenkins

current-context: jenkins-context

users:
- name: jenkins
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ik1XVzB3cExwZ0ZFYzNYcmplSkVTQ19UcFRGQ1E4aXRrVXNtTG95cWFYdlEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzg1MzIyNTU0LCJpYXQiOjE3ODUzMTg5NTQsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiOTljY2ZjODAtYjJjNy00Y2RjLWEyYWItN2FhYjhhOGUxOTIyIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMiLCJ1aWQiOiIzYjhhN2ViMC1mMzNiLTQyMzctYjZiOC1kZDdmOWRiMTFhOWYifX0sIm5iZiI6MTc4NTMxODk1NCwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6amVua2lucyJ9.nzom7FKMRszAOkFveNHSPYLSih5YCLH8E_iDFQOWikn3OrC-GoPXmSt_lTviUtGavICGfhalGgPF3IGZ4UFsAJr2AATNPP0C82aFARTwdt3r1BOpASpYQSy9d0GpFXFvGVsMk8mpXpAYdp1x9v7ZaNkmV3Yqu3l0JwJB5x3hzX0ORGQ-WYH6Qu132wqZ0S0SZy_KtwxCwmaMg5Zalr8gBD7yXJLIys3YhwMxuEGIPN--yb4LGzhZ1-1dtMII_0CoHOjS4mfKyFhXiAvTL9I4RADYyiEiJam2ijkfBBq4u86x0tVxW68KZloDqc6nYuoSyfvVpiYTVjnx13tY78-CQA