apiVersion: v1
kind: Config

clusters:
- name: minikube
  cluster:
    server: https://127.0.0.1:56078
    insecure-skip-tls-verify: true

users:
- name: minikube
  user:
    client-certificate: /root/.minikube/profiles/minikube/client.crt
    client-key: /root/.minikube/profiles/minikube/client.key

contexts:
- name: minikube
  context:
    cluster: minikube
    user: minikube

current-context: minikube