apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-frontend
  template:
    metadata:
      labels:
        app: library-frontend
    spec:
      containers:
      - name: frontend
        image: priyanshu907/library-frontend:v4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000